### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Hung369** [sendeniz/yolov1-real-time-obj-detection#2]
I've got this error announcement while running this command python train/train_yolov1.py.

Traceback (most recent call last):
  File "/workspaces/yolov1-real-time-obj-detection/train/train_yolov1.py", line 15, in <module>
    from utils.dataset import VOCData
  File "/workspaces/yolov1-real-time-obj-detection/utils/dataset.py", line 12, in <module>
    from utils.custom_transform import scale_translate, scale_translate_bounding_box
  File "/workspaces/yolov1-real-time-obj-detection/utils/custom_transform.py", line 7, in <module>
    import cv2 as cv
  File "/workspaces/yolov1-real-time-obj-detection/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/workspaces/yolov1-real-time-obj-detection/venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/python/3.10.13/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

 I followed all your steps and get stuck at training section. How can I fix this problem? Please, help me.
Thank you so much.

**Comment by sendeniz** [comment]
@Hung369 The error indicates that there is an issue with the system you are trying to run the model on. In particular with `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`. Have you tried `apt-get update && apt-get install libgl1` ? 
I am assuming you are running it on a local linux/unix machine?
If that doesnt help, please feel free to do a quick search query on solutions for this issue. Unfortunately, it is hard to debug such issues when I do not have access to your machine, but there is plenty of documentation about this error online. Keep me updated.

**Comment by Hung369** [comment]
It's works, thanks a lot.
